#!/bin/bash
export KBUILD_BUILD_USER=eraselk
export KBUILD_BUILD_HOST=gacorprjkt
echo $KBUILD_BUILD_USER
echo $KBUILD_BUILD_HOST
export LOCALVERSION="-justkernel"

export PATH="$(pwd)/gcc/bin:$PATH"
yawak=aarch64-linux-gnu-

make CROSS_COMPILE=$yawak ARCH=arm64 O=~/out nethunter_defconfig
make CROSS_COMPILE=$yawak ARCH=arm64 O=~/out -j16 \
        HEADER_ARCH=arm64 \
        SUBARCH=arm64 \
	CROSS_COMPILE=$yawak \
