#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_88XXAU)		+= rtl8812au/
# obj-$(CONFIG_RTL8188EU)		+= rtl8188eu/
obj-$(CONFIG_RTL8188EUS)				+= rtl8188eus/
obj-$(CONFIG_RTL8188FU)				+= rtl8188fu/
obj-$(CONFIG_RTL8192EU)				+= rtl8192eu/
obj-$(CONFIG_RTL8192FU)				+= rtl8192fu/
obj-$(CONFIG_RTL81812BU)				+= rtl8812bu/
obj-$(CONFIG_RTL8814AU)				+= rtl8814au/
