name: Build test

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 5
         
      - name: setup package
        run: |
         ./S
         
      - name: cloning KernelSU
        run: |
         curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.4

      - name: clean up
        run: |
         make clean; make mrproper; rm -rf out

      - name: check toolchain version
        run: |
         export PATH="./gcc/bin:$PATH"
         aarch64-elf-gcc -v
         
      - name: start up
        run: |
         ./build

      - name: anykernel ~ zipping
        run: |
         git clone --depth=1 https://github.com/bintang774/anykernel any
         cp out/arch/arm64/boot/Image.gz-dtb any
         cd any && zip -r9 kernel-${{ github.run_id }}.zip *
        
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
           files: |
            /home/runner/any/kernel-*
           name: Kernel-${{ github.run_id }}
           tag_name: ${{ github.run_id }}
        env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
