name: Build test

on:
  workflow_dispatch:
  watch:
    types: [started]

defaults:
  run:
    shell: bash

jobs:
  buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 5
         
      - name: Setup package
        run: |
          ./S
         
      - name: Cloning KernelSU
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.4

      - name: Clean up
        run: |
          make clean; make mrproper; rm -rf out

      - name: Check toolchain version
        run: |
          export PATH="./gcc/bin:$PATH"
          aarch64-elf-gcc -v

      - name: Start up
        run: |
          ./build

      - name: Verify output file
        run: |
          ls -R out/arch/arm64/boot/
        
      - name: AnyKernel ~ Zipping
        run: |
          if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
            git clone --depth=1 https://github.com/bintang774/anykernel any
            cp out/arch/arm64/boot/Image.gz-dtb any
            cd any && zip -r9 kernel-${{ github.run_id }}.zip *
          else
            echo "File Image.gz-dtb not found!"
            exit 1
          fi
        
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/runner/work/android_kernel_realme_mt6765/android_kernel_realme_mt6765/any/*.zip
          name: Kernel-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
